# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false

  config.vm.define "web" do |web|
      web.vm.network  "public_network", ip: "192.168.1.110"
      web.vm.hostname = "web"
      web.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = "2"
      end
  end

 config.vm.define "log" do |log|
     log.vm.network "public_network", ip: "192.168.1.115"
     log.vm.hostname = "log"
     log.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = "2"
     end
 end

 config.vm.define "rsyslogsrv" do |rsyslogsrv|
     rsyslogsrv.vm.network "public_network", ip: "192.168.1.120"
     rsyslogsrv.vm.hostname = "rsyslogsrv"
     rsyslogsrv.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = "2"
     end
 end

 config.vm.define "elk" do |elk|
     elk.vm.network "public_network", ip: "192.168.1.125"
     elk.vm.hostname = "elk"
     elk.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = "2"
     end
 end
end
